// @ts-nocheck
export {};
'use strict';

const fs = require('fs');
const path = require('path');

const {
  CODEX_MCP_QUICK_BLOCK,
  CODEX_INSTRUCTION_META
} = require('./main.templates.prompts.mcp');

function agentBlocks(agentHint) {
  return {
    agentHintBlock: agentHint ? `\n> This file is generated by AI CAD Companion Viewer for **${agentHint}**.\n` : '',
    codexQuickBlock: agentHint === 'OpenAI Codex' ? CODEX_MCP_QUICK_BLOCK : ''
  };
}

function readSkillContent(relativePath) {
  const candidates = [
    path.join(__dirname, relativePath),
    path.join(__dirname, '..', '..', 'electron', relativePath)
  ];
  const filePath = candidates.find((candidate) => fs.existsSync(candidate));
  if (!filePath) {
    throw new Error(`Missing bundled skill content: ${relativePath}`);
  }
  return fs.readFileSync(filePath, 'utf8');
}

const SKILL_CORE = {
  filename: 'aicad-core.mdc',
  description: 'AI CAD companion core project rules: geometry deliverables, layout, and validation policy',
  globs: '*',
  alwaysApply: true,
  content: readSkillContent('./skills/aicad-core-skill-content.md')
};

const SKILL_BUILD123D = {
  filename: 'skill-build123d.mdc',
  description: 'build123d CAD kernel syntax, API reference, parameterization, and structure policy',
  globs: '*.py',
  content: readSkillContent('./skills/build123d-skill-content.md')
};

const SKILL_MJCF = {
  filename: 'skill-mjcf.mdc',
  description: 'MJCF assembly rules for AI CAD, multi-body kinematics, and joint logic',
  globs: '*.xml',
  content: readSkillContent('./skills/aicad-mjcf-skill-content.md')
};

const SKILL_MCP_WORKFLOW = {
  filename: 'skill-mcp-workflow.mdc',
  description: 'MCP tools usage, generation protocol, accuracy contract, and failure recovery workflow',
  globs: '*',
  content: readSkillContent('./skills/aicad-mcp-skill-content.md')

};

const ALL_SKILLS = [SKILL_CORE, SKILL_BUILD123D, SKILL_MJCF, SKILL_MCP_WORKFLOW];

module.exports = {
  ALL_SKILLS,
  agentBlocks
};
