'use strict';

const {
  CODEX_MCP_QUICK_BLOCK,
  CODEX_INSTRUCTION_META
} = require('./main.templates.prompts.mcp');

function agentBlocks(agentHint) {
  return {
    agentHintBlock: agentHint ? `\n> This file is generated by AI CAD Companion Viewer for **${agentHint}**.\n` : '',
    codexQuickBlock: agentHint === 'OpenAI Codex' ? CODEX_MCP_QUICK_BLOCK : ''
  };
}

const SKILL_CORE = {
  filename: 'aicad-core.mdc',
  description: 'AI CAD companion core project rules: geometry deliverables, layout, and validation policy',
  globs: '*',
  alwaysApply: true,
  content: `## Most Important

When user says "make a gear" / "make a bracket", the deliverable is Python geometry code, not images:

- Build solid geometry in \`models/<model_name>/part.py\` using **build123d** and assign to global \`result\`.
- Store every tunable parameter in \`models/<model_name>/params.json\`; \`part.py\` and \`asm.xacro\` must read or substitute those values instead of hardcoding dimensions.
- Use \`asm.xacro\` for complex multi-part systems, articulated mechanisms, vehicles, robots, drones, tools with separable components, or anything whose intent implies multiple bodies. Do not collapse these into one monolithic \`part.py\`.
- In \`asm.xacro\`, visual geometry must reference exported meshes from existing part models through values in \`params.json\`; do not use URDF primitive shapes (\`box/cylinder/sphere\`) for final assembly deliverables.
- Do not create or rely on \`models/README.md\`; the file tree and UI are the project overview. Skip creating a README entirely unless the user explicitly requests documentation for a complex project.
- Do not ask user to create PNG/JPG as a substitute for CAD source.
- Preview flow is always code -> export_runner -> .brep; sequence is edit -> rebuild -> (optional) screenshot.
- **Silent Validation & Brief Response:** Validate your geometry silently using MCP tools. Do not narrate your validation steps, traceback, or internal reasoning to the user. Say "Model generated" and show the preview, only speaking up if you hit a design blocker requiring user input.

## Validation Policy (important)
- Do **not** run \`python part.py\`, \`python -m\`, \`python -c\`, \`pytest\`, \`uv run\`, or \`poetry run\` for generated code validation.
- Local Python/build123d/OCP environments may be missing and produce misleading results outside viewer flow.
- For assemblies, keep \`asm.xacro\` + \`params.json\` as the source of truth and validate through viewer rebuild/screenshot flow.
- The only valid path is: edit source -> \`rebuild_model\` -> inspect \`ok / stderr\` -> optional \`screenshot_model\` / \`get_model_info\`.
- If MCP is unavailable, ask the user to start AI CAD Companion Viewer instead of manual Python fallback.

## Project Layout

MCP is provided by **AI CAD Companion Viewer** while it is running. Any IDE-side MCP or companion rule files for a specific agent are created when you launch that agent from the viewer.

\`\`\`
./
|- .aicad/project.json         (kernel metadata: kernel = build123d)
|- models/
|  |- <model_name>/
|  |  |- part.py or asm.xacro  (model source, must define global result for part.py)
|  |  |- params.json           (all tunable parameters for this model)
|  |  |- README.md             (model description)
|- .cache/                     (viewer screenshots and transient artifacts, auto-generated, ignore in git)
\`\`\`
`
};

const SKILL_BUILD123D = {
  filename: 'skill-build123d.mdc',
  description: 'build123d CAD kernel syntax, API reference, parameterization, and structure policy',
  globs: '*.py',
  content: `## Parameterization & Structure Policy

1. All tunable variables must be stored in \`params.json\`; the active model source may bind local names from that JSON before geometry construction.
2. All derived parameters must be defined after the top parameter block and before geometric modeling.
3. You may use flat variables, dicts, or simple classes for parameters. Do not over-engineer with \`namedtuple\` unless necessary.
4. For Python models, preserve the scaffold sections in this order: \`# === Parameters ===\`, \`# === Derived Parameters ===\`, \`# === Geometry ===\`.
5. For Python models, geometry implementation belongs in \`# === Geometry ===\`.
6. Before detailed geometry, explicitly declare the model coordinate frame and viewing orientation: origin meaning, +X, +Y, +Z.
7. The coordinate frame must be screenshot-friendly: front / side / top / iso views should expose the key features.
8. Conflict priority: if "fix rebuild" and "parameterization refactor" conflict, restore \`rebuild_model\` success first.

## Must Follow (build123d)

1. One model per directory: \`models/<model_name>/\`.
2. \`part.py\` must define global variable \`result\` as build123d objects (Part / Solid / Compound / Sketch).
3. Do not call \`export_*()\` manually; exporting is handled by the Electron-side runner.
4. Default unit is millimeter (mm).
5. The active source file must load tunable values from \`params.json\` in the top \`# === Parameters ===\` block before geometry code.
6. Multi-entity build123d models must always use \`with BuildPart()\` plus \`add(...)\`; do not assemble multiple solids with ad-hoc free-form composition patterns.
7. Explicitly declare the coordinate frame before detailed geometry (e.g. +X right, +Y back, +Z up).
8. Geometry edits must stay inside \`# === Geometry ===\`. Do not hardcode dimensions here.

## Mental Model & Troubleshooting (build123d)

- **Mental Model**: Context-based. Use \`with BuildPart() as bp:\` to create a context. Objects created inside are automatically added.
- **Troubleshooting "Fillet / Chamfer failed"**: Radius/length is likely too large for the edges, or wrong edges selected. Reduce size or refine selector (e.g., \`edges().filter_by(Axis.Z)\`).

## Quick API Reference / Ammunition (build123d)

- **2D Sketches**: \`Circle(radius)\`, \`Rectangle(width, height)\`, \`RegularPolygon(radius, side_count)\`, \`SlotCenterToCenter(distance, radius)\`
- **3D Primitives**: \`Box(l, w, h)\`, \`Cylinder(radius, height)\`, \`Sphere(radius)\`, \`Cone(bottom_radius, top_radius, height)\`
- **Operations**: \`extrude(amount)\`, \`revolve(axis=Axis.Y)\`, \`sweep(path)\`
- **Locations & Arrays**: \`Pos(x, y, z)\`, \`Rot(x, y, z)\`, \`GridLocations(x_sp, y_sp, x_cnt, y_cnt)\`, \`PolarLocations(radius, count)\`
- **Modifiers**: \`fillet(edges(), radius)\`, \`chamfer(edges(), length)\`, \`Hole(radius, depth)\`
- **Contexts & Booleans**: \`with BuildPart() as bp:\`, \`with BuildSketch(bp.faces().sort_by(Axis.Z)[-1]):\`, \`add(obj, mode=Mode.SUBTRACT)\`
`
};

const SKILL_XACRO = {
  filename: 'skill-xacro.mdc',
  description: 'XACRO assembly rules for AI CAD, multi-body kinematics, and joint logic',
  globs: '*.xacro',
  content: `## Model Type Decision (explicit)

- Use \`part.py\` only for a single rigid body (brackets, gears, housings, standalone components).
- Use \`asm.xacro\` for complex multi-part systems, articulated structures, vehicles, robots, drones, tools with separable components, or any model composed from multiple reusable sub-parts.
- If the request describes multiple distinct bodies, moving/rotating components, repeated subassemblies, or kinematic relationships, choose \`asm.xacro\` by default.
- Do not satisfy complex multi-part requests by fusing everything into one monolithic \`part.py\`.
- In \`asm.xacro\`, each visual mesh must come from an existing part export (\`models/<part>/<part>.stl\`) referenced through \`params.json\`, then connect links via joints.

## Assembly Workflow

1. Create each reusable rigid body as its own \`models/<part_name>/part.py\`.
2. Rebuild each part so its exported mesh exists.
3. Create the top-level \`models/<assembly_name>/asm.xacro\` and \`models/<assembly_name>/params.json\`.
4. Reference part meshes from XACRO and connect links with joints.
5. Rebuild the assembly model and inspect the viewer output.

## Must Follow (XACRO)

1. Assembly source uses \`asm.xacro\` plus \`params.json\`.
2. \`asm.xacro\` visual geometry must reference meshes exported from existing part models in this project; do not use URDF primitive geometry tags (\`box\`, \`cylinder\`, \`sphere\`) in final assembly output.
3. Use \`\${...}\` substitutions in \`asm.xacro\` for names, mesh filenames, origins, scales, axes, and limits that can change.
4. For \`asm.xacro\`, define at least one non-fixed joint (\`continuous\`, \`revolute\`, or \`prismatic\`) whenever motion/actuation is part of the intent.
5. For rotating components in \`asm.xacro\`, prefer joint names that include \`prop\`, \`rotor\`, \`wheel\`, \`fan\`, or \`spin\` to improve preview animation defaults.
`
};

const SKILL_MCP_WORKFLOW = {
  filename: 'skill-mcp-workflow.mdc',
  description: 'MCP tools usage, generation protocol, accuracy contract, and failure recovery workflow',
  globs: '*',
  content: `## Accuracy Contract (mandatory)

1. **Evidence before conclusion**: cite MCP tool output before any geometric claim.
2. **Build before validation**: after editing the active model source, \`rebuild_model\` must pass first.
3. **Traceability**: explicitly mention tool evidence (at least one from \`rebuild_model\` + \`get_model_info\` / \`screenshot_model\`).
4. **No guesswork**: never claim dimensions/structure are correct without tool evidence.
5. **Keep it Simple**: For simple parts (flanges, brackets, primitives), write geometry directly and concisely without over-analyzing.

## Visual Recognition Features & Routing

- **For simple parts (e.g. flanges, basic brackets, enclosures):** Skip deep visual analysis and routing. Just declare parameters and build the geometry directly in one pass.
- **For complex organic or appearance-critical parts:** Briefly extract key visual features (overall silhouette, main symmetry, primary masses, edge language) before modeling to ensure recognizability. Route as \`profile-dominant\` (sketch-first) or \`mass-dominant\` (body-first) as appropriate.

## Generation Protocol

- **Simple Models:** Generate all geometry in a single pass (e.g. cylinder + hole + polar array of holes) and rebuild.
- **Complex Models (Two-Pass):** When creating heavily detailed models, build primary structure in Pass 1, verify with rebuild_model and screenshot_model, then add secondary features (fillets, chamfers, small cutouts) in Pass 2.

## Phased Workflow

1. Understand requirements: target geometry, dimensions, constraints.
2. Plan parameters first, declare the coordinate frame and viewing orientation.
3. Generate the structure (use single pass for simple parts, two passes for complex).
4. Build with \`rebuild_model({ model })\`; if it fails, follow failure recovery.
5. Validate with screenshots and numeric checks silently.
6. In the final answer, be extremely brief. Do not summarize your internal self-checks.

## Failure Recovery (when rebuild_model fails)

Follow this exact order:
1. Read \`stderr\` and locate the first deterministic error.
2. Apply the smallest possible fix (no unrelated refactor).
3. Immediately run \`rebuild_model({ model })\` again.
4. If parameterization cleanup conflicts with rebuild fix, prioritize rebuild success first and postpone refactor.
5. After success, then re-check with \`get_model_info\` / \`screenshot_model\` before final answer and style self-check.

## MCP Tools (viewer must be running)

The viewer exposes MCP server **aicad** on a local HTTP endpoint. Your IDE/agent loads that endpoint via its own project config; launch the matching agent from **AI CAD Companion Viewer** so those configs exist and the viewer is running.

| Tool | Purpose |
|---|---|
| \`list_models()\` | List all models and the current active model |
| \`get_model_info({ model })\` | Bounding box (mm), face count, and cache state |
| \`screenshot_model({ model, view? })\` | Single-view PNG (\`iso/front/side/top\`, default \`iso\`) |
| \`rebuild_model({ model })\` | Synchronous build with ok/stderr/faceCount/cacheSize |

Suggested workflow:
\`\`\`
if visual style matters:
    extract visual recognition features first
    # silhouette, proportions, symmetry, edge language, signature motifs
    ->
for a new Python model:
    decide model type first
    # single rigid body => models/<name>/part.py
    # complex multi-part / articulated / vehicle / robot / drone / separable components => models/<name>/asm.xacro + params.json plus reusable part.py models
    ->
    route the task
    # asm => body-first parts, then XACRO composition
    # part => profile-dominant => sketch-first
    # part => mass-dominant => body-first
    # if uncertain => body-first
    ->
    declare coordinate frame and viewing orientation
    # origin, +X, +Y, +Z, front/top/right
    ->
    Pass 1: generate only the primary structure
    ->
    rebuild_model({ model: "<model_name>" })
    ->
    screenshot_model({ model: "<model_name>", view: "iso" })
    ->
    if Pass 1 read is unclear:
        reroute once before adding detail
    ->
    Pass 2: add details only after Pass 1 screenshots read correctly
    ->
edit models/<name>/params.json plus models/<name>/part.py or asm.xacro
    ->
rebuild_model({ model: "<model_name>" })    # if failed, fix using stderr then retry
    ->
screenshot_model({ model: "<model_name>", view: "iso" }) # visual verification
    ->
if needed: get_model_info        # numeric checks
    ->
final answer: Just say "Model generated" and show the preview. Do not narrate internal checks.
\`\`\`
`
};

const ALL_SKILLS = [SKILL_CORE, SKILL_BUILD123D, SKILL_XACRO, SKILL_MCP_WORKFLOW];

module.exports = {
  ALL_SKILLS,
  agentBlocks
};
